package:
  name: lsstbroker
  version: "0.1"

source:
  path: .

requirements:
  build:
    - python
    - setuptools ==27.2.0
    - mysql-python
    - dask
    - toolz

  run:
    - python

about:
  home: https://github.com/CSC380Team8/lsst-event-broker
  license: GPLv3
  license_file: LICENSE
